trigger:
 paths:
   include:
     - terraform/*
pool:
 vmImage: 'ubuntu-latest'

variables:
  tfWorkingDir: terraform

stages:
  - stage: validate
    displayName: terraform-validate
    jobs:
      - job: validate
        steps:
        - checkout: Self
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        
          
        - task: AzureCLI@3
          inputs:
                connectionType: 'azureRM'
                azureSubscription: 'az-resource'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  ls -ltr
                  cd $(tfWorkingDir)
                  
                  terraform init
                  
                  terraform fmt -check
                  
                  terraform validate

  - stage: plan
    displayName: terraform plan
    dependsOn: validate
    jobs:
      - job: plan
        steps:
        - checkout: self
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        
        - task: AzureCLI@3
          inputs:
            connectionType: 'azureRM'
            azureSubscription: 'az-resource'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              cd $(tfworkingDir)
              terraform init
              terraform plan --var-file="dev.tfvars" -out=tfplan