trigger:
 branches:
   include:
     - main

variables:
   imageName: 
   acr: my1988vg
   repositry:  
     
stages:
  - stage: terraform
    jobs:
      - job: createinfra
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - script: |
              cd terraform
              terraform init
          - script: |
              cd terraform
              terraform validate
          - script: |    
              cd terraform
              terraform plan
          - script: |
              cd terraform
              terraform apply -auto-approve
            


      
