trigger:
 branches:
   include:
     - main

variables:
   imageName: myapp
   acr: vg1988myacr
   repositry:  
     
stages:
  - stage: terraform
    jobs:
      - job: createinfra
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - script: |
              set -x
              mkdir tfbin
              cd tfbin
              wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt update && sudo apt install terraform
          - task: AzureCLI@2
            inputs:
               azureSubscription: 'az-resource'
               scriptType: bash
               scriptLocation: inlineScript
               inlineScript: |
                 az account show
                 
                 cd terraform

                 ls -ltr

                 terraform init

                 terraform validate

                 terraform plan -var-file="dev.tfvars"

                 terraform apply -var-file="dev.tfvars" -auto-approve
  - stage: build
    dependsOn: terraform
    jobs:
      - job: build_push
        pool:
         vmImage: 'ubuntu-latest'
        steps:
           - task: AzureCLI@2
             inputs:
               connectionType: 'azureRM'
               azureSubscription: 'az-resource'
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                az acr login  --name $(acr)
                 docker build -t $(acr).azurecr.io/$(imageName):$(Build.BuildId) ./app
                 docker push $(acr).azurecr.io/$(imageName):$(Build.BuildId)
  - stage:  deploy
    dependsOn: build
    jobs:
     - job: deploy
       pool:
        vmImage: 'ubuntu-latest'
       steps:
         - task: KubernetesManifest@1
           inputs:
             action: 'deploy'
             connectionType: 'azureResourceManager'
             azureSubscriptionConnection: 'az-resource'
             azureResourceGroup: 'aks-rg'
             kubernetesCluster: 'myaks-cluster'
             namespace: 'dev'
             manifests: 'manifests'
             containers: 'vg1988myacr.azurecr.io/myapp:$(Build.BuildId)'
             imagePullSecrets: |
               az aks update \
                 --name myaks-cluster \
                 --resource-group aks-rg \
                 --attach-acr vg1988myacr
