trigger:
 branches:
   include:
     - main

variables:
   imageName: 
   acr: my1988vg
   repositry:  
     
stages:
  - stage: terraform
    jobs:
      - job: createinfra
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - script: |
              set -x
              mkdir tfbin
              cd tfbin
              wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt update && sudo apt install terraform
          - task: AzureCLI@2
            inputs:
               azureSubscription: 'az-resource'
               scriptType: bash
               scriptLocation: inlineScript
               inlineScript: |
                 az account show
                 
                 cd terraform

                 terraform init

                 terraform validate

                 terraform plan

                 terraform apply -var-file=dev.tfvars -auto-approve
