apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-sync
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "e9a3c747-623a-405b-928d-79a9a643171a" # Set the clientID of the user-assigned managed identity to use
    keyvaultName: myvault1988 # Set to the name of your key vault
    objects: |
      array:
        - |
          objectName: db-password           # keyvault secret name
          objectType: secret

        - |
          objectName: db-user1      # keyvault secret name
          objectType: secret

    tenantId: cf143a5c-8872-49f6-8651-4e40cf7a6a8e
