apiVersion : apps/v1
kind: Deployment
metadata:
  name: vajramgazuresampleapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vajramgazuresampleapp
  template:
    metadata:
      labels:
        app: vajramgazuresampleapp 
    spec:
      containers:
        - name: vajramgazuresampleapp 
          image: vg1988myacr.azurecr.io/vajramgazuresampleapp
          ports:
          - containerPort: 5000