apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-sync
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "5c29225f-111a-4372-9688-a2ab2a06db39" # Set the clientID of the user-assigned managed identity to use
    keyvaultName: myvg1988 # Set to the name of your key vault
    objects: |
      array:
        - |
          objectName: db-password           # keyvault secret name
          objectType: secret
    tenantId: 57b08271-f568-4659-9d9e-2776244a6b8c
